#!/bin/bash

# This program compiles and runs an OSP project

# Installation: Copy to your home directory and change the marked line below
# Usage: ~/osp ch99/MyJavaApp
# Note: Do not include the ".java" extension on your program's name

# The following line should point to your osp_project directory:
# cd ~/home/mnt756/osp_project
#javac -d classes/ -sourcepath src/ src/org/opensourcephysics/sip/$1.java && java -classpath classes/ org/opensourcephysics/sip/$1
# Added "-classpath classes/" option (necessary on Ken's laptop, running Mint linux):
# javac -d classes/ -classpath classes/ -sourcepath src/ src/org/opensourcephysics/sip/$1.java && java -classpath classes/ org/opensourcephysics/sip/$1
javac -d classes/ -classpath "classes/:lib/*" -sourcepath src/ src/org/opensourcephysics/sip/$1.java && java -classpath "classes/:lib/*" org/opensourcephysics/sip/$1

